In [34]:
import numpy as np
#on voudrait taille_en_cm/pas=nb_entier_impair=taillex (ou y)

#paramètres du problème
eta=0.001
mu=1000
tx=6 #à être défini par l'utilisateur , nb arbitraire pr l'instant
ty=3
taillex=2*tx+1 #taille tuyau
tailley=2*ty+1
#creation de la matrice A initiale
Nx = taillex+1 # "taille" désigne la taille du tuyau, Nx+1 et Ny+1 sont les dimentions de la matrice \ mais python commence le décompte des coordonées des coefficients à 0 (et non 1) donc c'est plus pratique
Ny = tailley+1
A=np.zeros((Ny+1, Nx+1)) #!!!jsp pk c Nx+1
for a in range(1,Nx+1,2): 
    for b in range(0,Ny+1,2):
        A[b,a]=1
dt=1
dx=1
dy=1
print(A)

[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]]


In [35]:
 #boucle infini selon tmp
#definition de Vx
for a in range(3,Nx-2,2): #a va de 3 à Nx-3 car les autres points sont hors du tuyau et servent de conditions initiales,sinon le laplacien n'est pas défini, calcul le long d'une ligne donc a est l'indice de la colonne
    for b in range(2,Ny-1,2):#b va de 2 à Ny-2, calcul le long d'une colonne 
        laplaVx=float((A[b,a+2]-A[b,a-2])/dx**2)
        derivp=float((A[b,a+1]-A[b,a-1])/dx)
        derivxVx2=float(((A[b,a+2])**2-(A[b,a])**2)/dx)
        derivyVx=float((A[b+2,a]-A[b,a])/dy)
        Vy=float(A[b-1,a-1])
        A[b,a]=A[b,a]+ dt*(-derivp+eta*laplaVx-derivxVx2-Vy*derivyVx)
        #faire un if difference entre mat < tolérence -> break

#definition de Vy 
for a in range(2,Nx-1,2): 
    for b in range(3,Ny-2,2): 
        laplaVx=float((A[b,a+2]-A[b,a-2])/dx**2)
        derivp=float((A[b,a+1]-A[b,a-1])/dx)
        derivyVy2=float(((A[b+2,a])**2-(A[b,a])**2)/dy)
        derivxVy=float((A[b,a+2]-A[b,a])/dx)
        Vx=float(A[b-1,a-1])
        A[b,a]=A[b,a]+ dt*(-derivp+eta*laplaVx-derivyVy2-Vx*derivxVy)
        
#correction de pression
for a in range(2,Nx-1,2): 
    for b in range(2,Ny-1,2): 
        div=(A[b,a+1]-A[b,a-1])/dx+(A[b+1,a]-A[b-1,a])/dy
        

